name: Run Tests 

on:
  push:
    branches:
      - '**'    # Run on push to any branch
  pull_request:
    branches:
      - main    # Run when a pull request is made to the main branch


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yaml
          activate-environment: mental-health
          python-version: 3.9

      - name: Install additional dependencies
        run: pip install pytest

      - name: Run tests with pytest
        run: |
          conda install pytest 
          conda install seaborn 
          python -m pip install --upgrade pip
          conda install numpy  
          conda install pandas 
          conda install matplotlib
          conda install scikit-learn
          conda install pycountry
          conda install scipy
          pytest --maxfail=1 --disable-warnings