name: Run Tests 

on:
  push:
    branches:
      - '**'    # Run on push to any branch
  pull_request:
    branches:
      - main    # Run when a pull request is made to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yaml
          activate-environment: mental-health
          python-version: 3.9  # Match the Python version in your `environment.yaml`

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install additional conda dependencies
        run: |
          conda install -y pytest pytest-mock flask flask-cors
          conda install -y seaborn numpy pandas matplotlib scikit-learn pycountry scipy

      - name: Install additional pip dependencies
        run: |
          pip install pytest pytest-mock flask flask-cors
          pip install seaborn numpy pandas matplotlib scikit-learn pycountry scipy

      - name: Run tests with pytest
        run: pytest --maxfail=1 --disable-warnings
